hk:
  ENV: staging
  ENV_CLUSTER: ap1
  ENV_ALLURE_URL:
  ENV_ALLURE_URL_LOCAL: http://localhost:9000/
  ENV_URL: https://ecom-api.ap1-staging.zeek.store/api/
  ENV_EC_APP_ID: "24"
  ENV_CLIENT_ID: colortea
  ENV_USER_ID: 1
  ENV_BRAND_ID: 2
  ENV_MEMBER_ID: "50"
  ENV_WEB_MEMBER_PHONE: "69090001"
  ENV_WEB_MEMBER_PWD: "Aa123456"
  ENV_COUPON_CODE: "131313"
  ENV_COUPON_CODE02: "10010"
  ENV_COUNTRY_CODE: "852"
  ENV_PHONE_NUMBER: "98989898"
  ENV_JWT_KEY: updatePasswordKeySalt0095
  ENV_SECRET: f6b13dea347b078d492bfccd7c426a11
  ENV_LANGUAGE: zh_hk
  ENV_REGION: HK
  ENV_UTC: 8
  ENV_STORE_ID: 2
  ENV_STORE_NAME: automated_test
  ENV_LOCATION_ID01: 14
  ENV_LOCATION_ID02: 12
  ENV_LOCATION_NAME: 茶颜悦色铜锣湾店（API专用）
  ENV_CATEGORY_ID: 319
  ENV_UPDATE_CATEGORY_ID: 320
  ENV_CATEGORY_PARENT_ID: 318
  ENV_PAYMENT_METHODS_KEY: paypal
  ENV_DEPARTMENT_ID: 27
  ENV_TIMESLOT_ID: 8
  ENV_PRODUCT_ID01: 667
  ENV_PRODUCT_ID02: 668
  ENV_PRODUCT_ID03: 669
  ENV_PRODUCT_ID04: 674
  ENV_UP_PRODUCT_ID: 670
  ENV_PRODUCT_IDS: 671,672
  ENV_ITEM_ID: 591
  ENV_OPTION_ID: 171
  ENV_OPTION_ID_02: 170
  ENV_UP_OPTION_ID: 172
  ENV_OPTION_VALUE_ID: 249
  ENV_OPTION_VALUE_ID02: 250
  ENV_OPTION_VALUE_TEXT: 今天应做的事没有做，明天再早也是耽误了
  ENV_COORDINATES: 22.2802695,114.1806216
  ENV_ORDER_ID: "24zk2022090989032"
  ENV_ADDRESS_TEXT: 香港铜锣湾轩尼诗道铜锣湾广场一期
  ENV_COUPON_ID: 15
  ENV_UP_COUPON_ID: 74
  # 用于「获取当前组织用户org/current_user」接口，其余接口ENV_TOKEN配置不需要填
  #ENV_TOKEN: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IntcInVzZXJfaWRcIjpcIjIyMlwiLFwiZWNfYXBwX2lkXCI6XCIyNFwiLFwiZXhwaXJlc19pblwiOjE2NTc2OTUyODYsXCJzY29wZXNcIjpbXCIqXCJdLFwiYXV0aF9wcm92aWRlclwiOlwiTWVyY2hhbnRcIn0i.JU51f8hqLOE3vBG7kjr4xW4kCRLTWuznVxOAUapS0Oc"
  ENV_TOKEN:
  ENV_WEB_TOKEN: